/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  admin?: string | null;
  lp_token_code_id: number;
  pool_code_id: number;
  protocol_fee_percent: Decimal;
  protocol_fee_recipient: string;
}
export type ExecuteMsg = {
  create_pool: {
    lp_fee_percent: Decimal;
    token1_denom: Denom;
    token2_denom: Denom;
  };
};
export type Denom = {
  native: string;
} | {
  cw20: Addr;
};
export type Addr = string;
export type QueryMsg = {
  get_pools: {};
};
export interface GetPoolsResponse {
  pools: string[];
}