name: React build on pull

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build react app
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint && npm run build
